# Generated by Django 3.1.7 on 2021-03-07 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('created',)},
        ),
    ]
