# Generated by Django 3.1.7 on 2021-03-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210307_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_picture',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
